account_id = ""
compatibility_date = "2022-04-01"
kv_namespaces = [
  {binding = "DATA", id = "b6357214ba6b43aab80f546d8ee68574", preview_id = "b6357214ba6b43aab80f546d8ee68574"},
]
main = "server.js"
name = "austincrim-dot-com"
type = "javascript"
workers_dev = true

[vars]
NOTION_POSTS_DB_ID = "c7c356ff282e40b796673c882578f689"
#NOTION_TOKEN

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
